### ISSUE TITLE
removing coverage?

### ISSUE THREAD

**Issue by tbenett** [tbenett/ruby-ipfs-http-client#51]
I'm considering removing coverall.

I don't think coverage as a metric, brings any value to a project.
- 100% covered code doesn't mean it is well tested and moreover it doesn't mean that it is bug-free.

But maybe I'm wrong what do you think?

**Comment by andrew** [comment]
I agree, it’s not a great metric, I’ve found the coverage reporters tend to just create noise rather than encouraging better tests

**Comment by tbenett** [comment]
Coveralls has been removed. Good riddance!

https://github.com/tbenett/ruby-ipfs-http-client/commit/128e841eb42c4b6a2f2a3b975e1e5a5cdbf4bebf
